avt_vimba_camera:
  ros__parameters:
    width: 640
    height: 400
    frame_id: map
    camera_ip_addr: 169.254.185.205
    acquisition_mode: Continuous
    acquisition_rate: 30
    balance_ratio_abs: 1.0
    balance_ratio_selector: Red
    binning_x: 1
    binning_y: 1
    decimation_x: 1
    decimation_y: 1
    exposure: 51000
    exposure_auto: Continuous
    exposure_auto_alg: FitRange
    exposure_auto_max: 50000
    exposure_auto_min: 41
    exposure_auto_outliers: 0
    exposure_auto_rate: 100
    exposure_auto_target: 50
    exposure_auto_tol: 5
    gain: 0
    gain_auto: Continuous
    gain_auto_max: 32
    gain_auto_min: 0
    gain_auto_outliers: 0
    gain_auto_rate: 100
    gain_auto_target: 50
    gain_auto_tol: 5
    iris_auto_target: 50
    iris_mode: Continuous
    iris_video_level_max: 110
    iris_video_level_min: 110
    pixel_format: BGR8Packed
    ptp_mode: 'Off'
    roi_height: 0
    roi_offset_x: 0
    roi_offset_y: 0
    roi_width: 0
    stream_bytes_per_second: 45000000
    sync_in_selector: SyncIn1
    sync_out_polarity: Normal
    sync_out_selector: SyncOut1
    sync_out_source: GPO
    trig_timestamp_topic: ''
    trigger_activation: RisingEdge
    trigger_delay: 0.0
    trigger_mode: 'On'
    trigger_selector: FrameStart
    trigger_source: FixedRate
    use_sim_time: false
    whitebalance_auto: Continuous
    whitebalance_auto_rate: 100
    whitebalance_auto_tol: 5
