# Dynamics Bicycle Model Parameters
model_params:
  cornering_stiffness_front: 130634.4
  cornering_stiffness_rear: 130634.4
  mass: 761.
  length_front: 1.54
  length_rear: 2.554
  yaw_moment_inertia: 550
  drag_coeff: 0.814

# Velocity Brackets to generate [m/s]
# feedback matrices from
# Q: [ lateral_error, lateral_error_dot, yaw_error, yaw_error_dot, v_error ]
# lateral_error : for reducing cross-track error
# lateral_error_dot : for enforcing ego vehicle inner side w.r.t. reference trajectory (during cornering)
velocity_brackets:
- velocity: 10
  q_trace: [5.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 50.]
- velocity: 20
  q_trace: [4.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [350., 50.]
- velocity: 25
  q_trace: [2.5, 0.5, 0.1, 0.0, 5.0]
  r_trace: [800., 50.]
- velocity: 30
  q_trace: [1.2, 0.2, 0.1, 0.0, 5.0]
  r_trace: [950., 50.]
- velocity: 35
  q_trace: [1.0, 0.1, 0.1, 0.0, 5.0]
  r_trace: [1100., 50.]
- velocity: 40
  q_trace: [1.0, 0.08, 0.1, 0.0, 5.0]
  r_trace: [1300., 60.]
- velocity: 45
  q_trace: [1.0, 0.06, 0.1, 0.0, 5.0]
  r_trace: [1500., 70.]
- velocity: 50
  q_trace: [1.0, 0.04, 0.1, 0.0, 5.0]
  r_trace: [1700., 80.]
- velocity: 55
  q_trace: [1.0, 0.02, 0.1, 0.0, 5.0]
  r_trace: [1900., 90.]
- velocity: 60
  q_trace: [1.0, 0.01, 0.1, 0.0, 5.0]
  r_trace: [2100., 100.]