# Dynamics Bicycle Model Parameters
model_params:
  cornering_stiffness_front: 130634.4
  cornering_stiffness_rear: 130634.4
  mass: 761.
  length_front: 1.54
  length_rear: 2.554
  yaw_moment_inertia: 550
  drag_coeff: 0.814

# Velocity Brackets to generate [m/s]
# feedback matrices from
# Q: [ lateral_error, lateral_error_dot, yaw_error, yaw_error_dot, v_error ]
velocity_brackets:
- velocity: 10
  q_trace: [5.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 20
  q_trace: [4.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 30
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 35
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 40
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 45
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 50
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 55
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]
- velocity: 60
  q_trace: [3.0, 1.0, 0.1, 0.0, 5.0]
  r_trace: [250., 100.]