#!/usr/bin/env bash
. /opt/ros/foxy/setup.bash

colcon build --base-paths src/* "$@" --cmake-args -DCMAKE_INSTALL_PREFIX=/home/$USER/nif/install

. install/setup.bash
ros_env="AMENT_PREFIX_PATH CMAKE_PREFIX_PATH COLCON_PREFIX_PATH PKG_CONFIG_PATH PYTHONPATH LD_LIBRARY_PATH PATH ROS_DISTRO ROS_PYTHON_VERSION ROS_LOCALHOST_ONLY ROS_VERSION"
env_string=""
for e in ${ros_env}; do
    env_string+="$e=${!e};"
done
echo "$env_string"
