#!/usr/bin/env bash

. /opt/ros/foxy/setup.bash
sudo apt update

# Import external repos
GL_TOKEN=$(cat .secret.gitlab) bash -c 'cat nif.foxy.repos | envsubst > nif.foxy.repos.tmp'
vcs import < nif.foxy.repos.tmp --workers=1
rm nif.foxy.repos.tmp

# Install python dependencies
pip install -r central-requirements.txt


rosdep update
rosdep install -ir -y --from-path src/ --rosdistro $ROS_DISTRO
