/**:
  ros__parameters:
    frames:
      body: "rear_axle_middle"
      global: "map"

      gps_top: "gps_top"
      gps_bottom: "gps_bottom"

      luminar_left: "luminar_left"
      luminar_front: "luminar_front"
      luminar_right: "luminar_right"

      camera_front_1: "camera_front_1"
      camera_front_left: "camera_front_left"
      camera_front_right: "camera_front_right"
      camera_front_2: "camera_front_2"
      camera_rear_left: "camera_rear_left"
      camera_rear_right: "camera_rear_right"

      radar_front: "radar_front"
      radar_port: "radar_port"
      radar_starboard: "radar_starboard"
      radar_rear: "radar_rear"