builtin_interfaces/Time stamp
uint8 base_to_car_heartbeat

uint8 TRACK_FLAG_NULL=0
uint8 TRACK_FLAG_RED=1
uint8 TRACK_FLAG_YELLOW=2
uint8 TRACK_FLAG_ORANGE=3
uint8 TRACK_FLAG_GREEN=4
uint8 track_flag

uint8 VEH_FLAG_NULL=0
uint8 VEH_FLAG_BLANK=1
uint8 VEH_FLAG_BLACK=2
uint8 VEH_FLAG_CHECKERED=4
uint8 VEH_FLAG_PURPLE=8
uint8 veh_flag

uint8 veh_rank
float32 lap_status_whole
float32 lap_status_fraction