/**:
  ros__parameters:
    race_wpt_path: 'maps/lgsvl_sim/lg_sim_racing_line.csv'
    pit_wpt_path: 'maps/lgsvl_sim/pit_lane_noyaw.csv'
    spline_interval: 1.0 # in [m]
    maptrack_size: 200 # in index level