/**:
  ros__parameters:
    race_wpt_path: 'maps/lgsvl_sim/race_line.csv'
    pit_wpt_path: 'maps/lgsvl_sim/pit_lane.csv'
    warmup_wpt_path: 'maps/lgsvl_sim/warm_up_wpt.csv'
    spline_interval: 1.0 # in [m]
    maptrack_size: 200 # in index level
