/**:
  ros__parameters:
    race_wpt_path: 'maps/LVMS/centerline.csv'
    pit_wpt_path: 'maps/LVMS/pit_lane.csv'
    warmup_wpt_path: 'maps/LVMS/centerline.csv'
    spline_interval: 1.0 # in [m]
    maptrack_size: 200 # in index level
