/**:
  ros__parameters:
    frames:
      body: "base_link"
      global: "map"

      gps_top: "gps_top"
      gps_bottom: "gps_bottom"

      luminar_left: "luminar_left"
      luminar_front: "luminar_front"
      luminar_right: "luminar_right"

      camera_front_1: "camera_front_1"
      camera_front_left: "camera_front_left"
      camera_front_right: "camera_front_right"
      camera_front_2: "camera_front_2"
      camera_rear_left: "camera_rear_left"
      camera_rear_right: "camera_rear_right"

      radar_front: "radar_front"
      radar_port: "radar_port"
      radar_starboard: "radar_starboard"
      radar_rear: "radar_rear"

    topics:
      ego_odometry: /localization/ekf/odom
        # bvs_localization/ltp_odom #
      #     localization/ego_odom
      system_status: system/status
      race_control_status: /raptor_dbw_interface/rc_to_ct
      ego_powertrain_status: /raptor_dbw_interface/pt_report

      node_status_prefix: /node_status/

    time:
      period_node_status_us: 40000

    coordinates:
      use_enu: false

      sim_ref_x: -1.727
      sim_ref_y: 21.37
      sim_ref_z: 0.119

      loc_ref_x: -314.766
      loc_ref_y: 24.387
      loc_ref_z: -0.0817

      # ecef_ref_lat: 39.8125900071711  #LOR
      # ecef_ref_lon: -86.3418060783425 #LOR      
      # ecef_ref_hgt: 0.0

      ecef_ref_lat: 39.809786 #IMS
      ecef_ref_lon: -86.235148 #IMS
      ecef_ref_hgt: -0.170035537