gating_thres: 19.22
gate_probability: 0.99
detection_probability: 0.9
life_time_thres: 30
merge_distance_threshold: 3.0
static_velocity_thres: 0.5
static_num_history_thres: 3
prevent_explosion_thres: 750 #1000
use_sukf: false
tracking_frame: "odom"