/**:
  ros__parameters:
    file_path_list:
#      - 'maps/LOR_inside_line.csv'
#      - 'maps/2021-08-06_LOR/LOR_earth_rl.csv'
      - 'maps/lgsvl_sim/lg_sim_racing_line.csv'
#      - 'maps/lgsvl_sim/wpt_left_filtered.csv'
#      - 'maps/lgsvl_sim/wpt_manual_points.csv'
#      - 'maps/lgsvl_sim/wpt_right.csv'
#      - 'maps/lgsvl_sim/wpt_right_filtered.csv'
    spline_interval:
      - 1.0 # in [m]
    maptrack_size:
      - 200 # in index level