# Misison codes are specified in nif_msgs/msg/MissionStatus.msg
# Velocities are expressed in meter per seconds [m/s]
# Listed conditions must have an 'active' flag. If false, the condition is ignored.
# fallback_mission_code is used in case pf rejection
missions:
  - mission_code: 0 # MISSION_RACE
    active: true
    fallback:
      active: true
      mission_code: 128 # MISSION_SLOW_DRIVE
    allowed_transitions:
      active: true
      from:
        - 0   # MISSION_RACE
        - 75  # MISSION_PIT_TO_TRACK
        - 128 # MISSION_SLOW_DRIVE
        - 200 # MISSION_COMMANDED_STOP
        - 400 # MISSION_COLLISION_AVOIDNACE
        - 500 # MISSION_WARMUP
        - 777 # MISSION_TEST

  - mission_code: 400 # MISSION_COLLISION_AVOIDNACE
    active: true
    fallback:
      active: true
      mission_code: 128 # MISSION_SLOW_DRIVE
    allowed_transitions:
      active: true
      from:
        - 0   # MISSION_RACE
        - 75  # MISSION_PIT_TO_TRACK
        - 128 # MISSION_SLOW_DRIVE
        - 200 # MISSION_COMMANDED_STOP
        - 400 # MISSION_COLLISION_AVOIDNACE
        - 777 # MISSION_TEST

  - mission_code: 500 # MISSION_WARMUP
    active: true
    fallback:
      active: true
      mission_code: 128 # MISSION_SLOW_DRIVE
    allowed_transitions:
      active: true
      from:
        - 0   # MISSION_RACE
        - 75  # MISSION_PIT_TO_TRACK
        - 128 # MISSION_SLOW_DRIVE
        - 200 # MISSION_COMMANDED_STOP
        - 500 # MISSION_WARMUP
        - 777 # MISSION_TEST


  - mission_code: 777 # MISSION_TEST
    active: true
    fallback:
      active: true
      mission_code: 128 # MISSION_SLOW_DRIVE
    allowed_transitions:
      active: true
      from:
        - 0   # MISSION_RACE
        - 75  # MISSION_PIT_TO_TRACK
        - 128 # MISSION_SLOW_DRIVE
        - 200 # MISSION_COMMANDED_STOP
        - 777 # MISSION_TEST

  - mission_code: 60 # MISSION_PIT_IN
    active: true
    fallback:
      active: true
      mission_code: 128 # MISSION_SLOW_DRIVE
    activation_area:
      active: true
      # bboxes:
      #   - - -0.0 # x_min
      #     - 0.0 # y_min
      #     - 10.0 # x_max
      #     - 10.0 # y_max
      polygons:
        - - x: 375.0  # x_0
            y: 100.0  # y_0
          - x: 500.0  # x_1
            y: 200.0  # y_1
          - x: 625.0  # x_2
            y: 100.0  # y_2
          - x: 500.0  # x_3
            y: 000.0  # y_3
    activation_velocity:
      active: true
      range_mps:
        - 0.0 # min m/s
        - 30.0 # max m/s
    allowed_transitions:
      active: true
      from:
        - 0   # MISSION_RACE
        - 50  # MISSION_STANDBY
        - 60  # MISSION_PIT_IN
        - 128 # MISSION_SLOW_DRIVE
        - 200 # MISSION_COMMANDED_STOP
        - 250 # MISSION_EMERGENCY_STOP
        - 400 # MISSION_COLLISION_AVOIDNACE
        - 500 # MISSION_WARMUP
        - 777 # MISSION_TEST
        - 65000 # MISSION_PIT_INIT
    timeout:
      active: false # ignored
      duration_ms: 1000

  - mission_code: 65 # MISSION_PIT_STANDBY
    active: true
    fallback:
      active: true
      mission_code: 60 # MISSION_PIT_IN
    activation_area:
      active: true
      polygons:
        - - x: -50.0  # x_0
            y: 000.0  # y_0
          - x: 000.0  # x_1
            y: 050.0  # y_1
          - x: 050.0  # x_2
            y: 000.0  # y_2
          - x: 000.0  # x_3
            y: -50.0  # y_3
    activation_velocity:
      active: false
      range_mps:
        - 0.000 # min m/s
        - 0.001 # max m/s
    allowed_transitions:
      active: true # ignore
      from:
        - 60    # MISSION_PIT_IN
        - 65    # MISSION_PIT_STANDBY
        - 70    # MISSION_PIT_OUT (Enables pit in from PIT_INIT)
        - 65000 # MISSION_PIT_INIT
    timeout:
      active: false # ignored
      duration_ms: 0

  - mission_code: 50 # MISSION_STANDBY
    active: true
    fallback:
      active: true
      mission_code: 200 # MISSION_COMMANDED_STOP
    activation_velocity:
      active: true
      range_mps:
        - 0.000 # min m/s
        - 0.001 # max m/s

  - mission_code: 70 # MISSION_PIT_OUT
    active: true
    # fallback: # CAN'T BE ACTIVE, IT CLOSES THE LOOP
    #   active: true
    #   mission_code: 65 # MISSION_PIT_STANDBY
    allowed_transitions:
      active: true
      from:
        - 70 # MISSION_PIT_OUT
        - 65 # MISSION_PIT_STANDBY
        - 65000 # MISSION_PIT_INIT

  - mission_code: 75 # MISSION_PIT_TO_TRACK
    active: true
    fallback:
      active: true
      mission_code: 70 # MISSION_PIT_OUT
    activation_area:
      active: true
      polygons:
        - - x: 100.0  # x_0
            y: -500.0  # y_0
          - x: 225.0 # x_1
            y: -400.0  # y_1
          - x: 250.0  # x_2
            y: -500.0  # y_2
          - x: 125.0  # x_3
            y: -575.0  # y_3
    allowed_transitions:
      active: true # ignore
      from:
        - 65 # MISSION_PIT_STANDBY
        - 70 # MISSION_PIT_OUT
        - 75 # MISSION_PIT_TO_TRACK
        - 65000 # MISSION_PIT_INIT

    timeout:
      active: false # ignored
      duration_ms: 0

  - mission_code: 128 # MISSION_SLOW_DRIVE
    active: true
    fallback:
      active: true
      mission_code: 75 # MISSION_PIT_TO_TRACK
    allowed_transitions:
      active: true # ignore
      from:
        - 0   # MISSION_RACE
        - 50  # MISSION_STANDBY
        - 75  # MISSION_PIT_TO_TRACK
        - 200 # MISSION_COMMANDED_STOP
        - 128 # MISSION_SLOW_DRIVE
        - 400 # MISSION_COLLISION_AVOIDNACE
        - 500 # MISSION_WARMUP
        - 777 # MISSION_TEST

  - mission_code: 65000 # MISSION_PIT_INIT
    active: true
    fallback:
      active: true
      mission_code: 50000 # MISSION_INIT
    activation_area:
      active: true
      polygons:
        - - x: -150.0  # x_0
            y: -120.0  # y_0
          - x: -50.0  # x_1
            y: 000.0  # y_1
          - x: 000.0  # x_2
            y: 050.0  # y_2
          - x: 200.0  # x_3
            y: 150.0  # y_3
          - x: 275.0  # x_4
            y: 150.0  # y_4
          - x: -150.0  # x_5
            y: -200.0  # y_5

    allowed_transitions:
      active: false
      from:
        - 65535   # MISSION_DEFAULT

  - mission_code: 50000 # MISSION_INIT
    active: true
    allowed_transitions:
      active: false
      from:
        - 65535   # MISSION_DEFAULT

