# Zones list for a specific track.
zones:
  - id: 0
    type: 0
    dynamics:  
      long_acceleration_max: 12.0
      long_acceleration_min: -12.0
    polygon:
      - x: 440.00 # x_0
        y: -95.00 # y_0
      - x: 720.00 # x_1
        y: -265.00 # y_1
      - x: 670.00 # x_2
        y: -315.00 # y_2
      # - x: 640.00 # x_3
      #   y: -295.00 # y_3
      - x: 550.0  # x_4
        y: -200.0 # y_4
      - x: 400.0 # x_5
        y: -125.0 # y_5

  - id: 1
    type: 20
    dynamics:  
      long_acceleration_max: 8.0
      long_acceleration_min: -4.0
    polygon:
      - x: 400.0 # x_0
        y: -125.0 # y_0
      - x: 300.0  # x_1
        y: -125.0  # y_1
      - x: 165.00 # x_2
        y: -175.00 # y_2
      - x: 125.00 # x_3
        y: -115.00 # y_3
      - x: 275.00 # x_4
        y: -70.00 # y_4
      - x: 440.00 # x_5
        y: -95.00 # y_5

  - id: 2
    type: 20
    dynamics:  
      long_acceleration_max: 8.0
      long_acceleration_min: -4.0
    polygon:
      - x: 165.00 # x_0
        y: -175.00 # y_0
      - x: 110.00 # x_1
        y: -355.00 # y_1
      - x: 35.00 # x_2
        y: -375.00 # y_2
      - x: 40.00 # x_3
        y: -265.00 # y_3
      - x: 125.00 # x_4
        y: -115.00 # y_4

  - id: 3
    type: 30
    dynamics:  
      long_acceleration_max: 10.0
      long_acceleration_min: -6.0
    polygon:
      - x: 110.00 # x_0
        y: -355.00 # y_0
      - x: 35.00 # x_1
        y: -375.00 # y_1
      - x: 65.00 # x_1
        y: -470.00 # y_1
      - x: 140.00 # x_3
        y: -445.00 # y_3

  - id: 4
    type: 0
    dynamics:  
      long_acceleration_max: 12.0
      long_acceleration_min: -12.0
    polygon:
      - x: 140.00 # x_0
        y: -445.00 # y_0
      - x: 65.00 # x_1
        y: -470.00 # y_1
      - x: 240.00 # x_2
        y: -695.00 # y_2
      - x: 290.00 # x_3
        y: -645.00 # y_3

  - id: 5
    type: 0
    dynamics:  
      long_acceleration_max: 12.0
      long_acceleration_min: -12.0
    polygon:
      - x: 290.00 # x_0
        y: -645.00 # y_0
      - x: 465.00 # x_1
        y: -845.00 # y_1
      - x: 440.00 # x_2
        y: -895.00 # y_2
      - x: 240.00 # x_3
        y: -695.00 # y_3

  - id: 6 
    type: 20
    dynamics:  
      long_acceleration_max: 8.0
      long_acceleration_min: -4.0
    polygon:
      - x: 465.00 # x_0
        y: -845.00 # y_0
      - x: 440.00 # x_1
        y: -895.00 # y_1
      - x: 620.00 # x_2
        y: -950.00 # y_2
      - x: 770.00 # x_3
        y: -875.00 # y_3
      - x: 730.00 # x_4
        y: -830.00 # y_4

  - id: 7
    type: 20
    dynamics:  
      long_acceleration_max: 8.0
      long_acceleration_min: -4.0
    polygon:
      - x: 770.00 # x_0
        y: -875.00 # y_0
      - x: 730.00 # x_1
        y: -830.00 # y_1
      - x: 790.00 # x_2
        y: -745.00 # y_2
      - x: 840.00 # x_3
        y: -775.00 # y_3

  - id: 8
    type: 30
    dynamics:  
      long_acceleration_max: 10.0
      long_acceleration_min: -6.0
    polygon:
      - x: 790.00 # x_0
        y: -745.00 # y_0
      - x: 840.00 # x_1
        y: -775.00 # y_1
      - x: 845.00 # x_2
        y: -615.00 # y_2
      - x: 810.0  # x_3
        y: -625.0  # y_3

  - id: 9
    type: 0
    dynamics:  
      long_acceleration_max: 12.0
      long_acceleration_min: -12.0
    polygon:
      - x: 720.00 # x_0
        y: -265.00 # y_0
      - x: 670.00 # x_1
        y: -315.00 # y_1
      - x: 725.0  # x_2
        y: -400.0  # y_2
      - x: 810.0  # x_3
        y: -625.0  # y_3
      - x: 845.00 # x_4
        y: -615.00 # y_4

  - id: 65000
    type: 65000
    dynamics:  
      long_acceleration_max: 6.0
      long_acceleration_min: -12.0
    polygon:
      - x: 400.0  # x_0
        y: -125.0  # y_0
      - x: 550.0  # x_1
        y: -200.0  # y_1
      - x: 725.0  # x_2
        y: -400.0  # y_2
      - x: 810.0  # x_3
        y: -625.0  # y_3
      - x: 750.0  # x_4
        y: -625.0  # y_4
      - x: 300.0  # x_5
        y: -125.0  # y_5

