# Zones list for a specific track. Currently, only bboxes are supported for zone definitions.
zones:
  - id: 0
    bbox:
      - -2100.0 # x_min
      - 250.0 # y_min
      - -1600.0 # x_max
      - 350.0 # y_max

  - id: 5
    bbox:
      - -1600.0 # x_min
      - -500.0 # y_min
      - -1200.0 # x_max
      - -300.0 # y_max
