# Zones list for a specific track. Currently, only bboxes are supported for zone definitions.
zones:
  - id: 0
    bbox:
      - 0.0 # x_min
      - 0.0 # y_min
      - 1.0 # x_max
      - 1.0 # y_max
    polygon:
      - x: 000.0  # x_0
        y: 500.0  # y_0
      - x: 300.0  # x_1
        y: 750.0  # y_1
      - x: 400.0  # x_2
        y: 600.0  # y_2
      - x: 110.0  # x_3
        y: 380.0  # y_3
  - id: 5
    bbox:
      - 0.0 # x_min
      - 0.0 # y_min
      - 1.0 # x_max
      - 1.0 # y_max
    polygon:
      - x: 600.0  # x_0
        y: 300.0  # y_0
      - x: 850.0  # x_1
        y: 500.0  # y_1
      - x: 950.0  # x_2
        y: 400.0  # y_2
      - x: 650.0  # x_3
        y: 200.0  # y_3