# Zones list for a specific track. Currently, only bboxes are supported for zone definitions.
zones:
  - id: 0
    polygon:
      - x: 500.0  # x_0
        y: -000.0  # y_0
      - x: 750.0  # x_1
        y: -300.0  # y_1
      - x: 600.0  # x_2
        y: -400.0  # y_2
      - x: 380.0  # x_3
        y: -110.0  # y_3
  - id: 1
    polygon:
      - x: 500.0  # x_0
        y: -000.0  # y_0
      - x: 750.0  # x_1
        y: -300.0  # y_1
      - x: 600.0  # x_2
        y: -400.0  # y_2
      - x: 380.0  # x_3
        y: -110.0  # y_3
  - id: 2
    polygon:
      - x: 500.0  # x_0
        y: -000.0  # y_0
      - x: 750.0  # x_1
        y: -300.0  # y_1
      - x: 600.0  # x_2
        y: -400.0  # y_2
      - x: 380.0  # x_3
        y: -110.0  # y_3
  - id: 3
    polygon:
      - x: 500.0  # x_0
        y: -000.0  # y_0
      - x: 750.0  # x_1
        y: -300.0  # y_1
      - x: 600.0  # x_2
        y: -400.0  # y_2
      - x: 380.0  # x_3
        y: -110.0  # y_3
  - id: 4
    polygon:
      - x: 500.0  # x_0
        y: -000.0  # y_0
      - x: 750.0  # x_1
        y: -300.0  # y_1
      - x: 600.0  # x_2
        y: -400.0  # y_2
      - x: 380.0  # x_3
        y: -110.0  # y_3
  - id: 5
    polygon:
      - x: 300.0  # x_0
        y: -600.0  # y_0
      - x: 500.0  # x_1
        y: -850.0  # y_1
      - x: 400.0  # x_2
        y: -950.0  # y_2
      - x: 200.0  # x_3
        y: -650.0  # y_3
  - id: 6
    polygon:
      - x: 300.0  # x_0
        y: -600.0  # y_0
      - x: 500.0  # x_1
        y: -850.0  # y_1
      - x: 400.0  # x_2
        y: -950.0  # y_2
      - x: 200.0  # x_3
        y: -650.0  # y_3
  - id: 7
    polygon:
      - x: 300.0  # x_0
        y: -600.0  # y_0
      - x: 500.0  # x_1
        y: -850.0  # y_1
      - x: 400.0  # x_2
        y: -950.0  # y_2
      - x: 200.0  # x_3
        y: -650.0  # y_3
  - id: 8
    polygon:
      - x: 300.0  # x_0
        y: -600.0  # y_0
      - x: 500.0  # x_1
        y: -850.0  # y_1
      - x: 400.0  # x_2
        y: -950.0  # y_2
      - x: 200.0  # x_3
        y: -650.0  # y_3