nif_aw_localization_nodes:
  ros__parameters:
    show_debug_info : false,
    predict_frequency : 50.0,
    tf_rate : 10.0,
    enable_yaw_bias_estimation : true,
    extend_state_step : 50,
    # pose_frame_id : :odom,
    # final_output_odom_name : :string,

    pose_additional_delay : 0.0,
    pose_measure_uncertainty_time : 0.01,
    pose_rate : 10.0,
    pose_gate_dist : 10000.0,
    pose_stddev_x : 0.05,
    pose_stddev_y : 0.05,
    pose_stddev_yaw : 0.035,
    use_pose_with_covariance : false,

    twist_additional_delay : 0.0,
    twist_rate : 100.0,
    twist_gate_dist : 10000.0,
    twist_stddev_vx : 0.2,
    twist_stddev_wz : 0.03,
    use_twist_with_covariance : false,

    proc_stddev_yaw_c : 0.005,
    proc_stddev_yaw_bias_c : 0.001,
    proc_stddev_vx_c : 2.0,
    proc_stddev_wz_c : 0.2,

