luminar_driver:
  ros__parameters:
    # the fingerprint ID of the sensor head we're using with this file 43200 11023
    lidar_fingerprint: 11023

    # when True, will expect sensor data to come from PCAP player app @localhost
    # when False, will use physical sensor
    data_source_is_pcap_app: True

    # full-field scan rate (1 to 30 Hz)
    scan_rate_hz: 10.0
   
    # scanning vertical field of view in degrees (range(<=30), center(-15 to 15), range+center cannot exceed +/-15)
    scan_fov: [30.0, 0.0]

    # scan_pattern can be: Gaussian, Trapezoidal, Uniform, Horizon, Exponential
    scan_pattern: ["Gaussian", "0.0", "10.0", "900.0"]

    # coordinate type: "Cartesian" or "Spherical" (Spherical has lower latency)
    coordinate_type: "Cartesian"

    # base topic name for this lidar's pointcloud
    lidar_topic_name: "front_lidar"

    # frame ID for the lidar
    lidar_frame_id: "map"

    # When True, this swaps the Y and Z positions and scales the reflectance of 
    # each data point for easier viewing in RViz, but the latency increases
    rviz_friendly: True

    # pose is: position (X,Y,Z (meters)), orientation(pitch, roll, yaw (radians))
    # pose transformation is CPU-expensive; leave at 0.0 to disable
    lidar_sensor_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # if False, data are published with sensor data QoS. This is preferrable
    # for production but default QoS is needed for rosbag.
    # See: https://github.com/ros2/rosbag2/issues/125
    use_system_default_qos: False

    # Mask-like-string used to define the data processors that should be
    # activated upon startup of the driver. This will determine the topics
    # that are available for client applications to consume. The defacto
    # reference for these values are defined in:
    # `include/ros2_luminar/H3/processor_factories.hpp`
    #
    # The available data processors are:
    # PCL   - Provides a point cloud encoding of a LiDAR scan
    h3_proc_mask: PCL

    # Lidar buffer size. Default to 12MB, since at a 1Hz update rate, the unit
    # can produce ~702K points, needing 11.2M bytes.
    buffer_size: 12582912
