luminar_driver_lr:
  ros__parameters:
    # the fingerprint ID of the sensor head we're using with this file 
    #lidar_fingerprint: 10724 
    lidar_fingerprint: 10422

    # when True, will expect sensor data to come from PCAP player app @localhost
    # when False, will use physical sensor
    data_source_is_pcap_app: False

    # port number for PCAP player. default 5118.
    pcap_port: 5122

    # full-field scan rate (1 to 30 Hz)
    scan_rate_hz: 20.0
   
    # scanning vertical field of view in degrees (range(<=30), center(-15 to 15), range+center cannot exceed +/-15)
    scan_fov: [15.0, -3.0]

    # scan_pattern can be: Gaussian, Trapezoidal, Uniform, Horizon, Exponential
    scan_pattern: ["Gaussian", "0.0", "1.0", "900.0"]

    # coordinate type: "Cartesian" or "Spherical" (Spherical has lower latency)
    coordinate_type: "Cartesian"

    # base topic name for this lidar's pointcloud
    lidar_topic_name: "luminar_left_points"

    # frame ID for the lidar
    lidar_frame_id: "luminar_left"

    # When True, this swaps the Y and Z positions and scales the reflectance of 
    # each data point for easier viewing in RViz, but the latency increases
    # NOTE: Set True to keep x-forward convention
    rviz_friendly: True

    # pose is: position (X,Y,Z (meters)), orientation(pitch, roll, yaw (radians))
    # pose transformation is CPU-expensive; leave at 0.0 to disable
    lidar_sensor_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # vehicle_polygon is a rectangle specified as [xMin, xMax, yMin, yMax] in meters
    # relative to the same base as the pose-corrected XYZ lidar coordinates.
    # lidar points that fall within this rectangle will be dropped from the sample
    # leave at 0.0 to disable.
    vehicle_polygon: [ -1.5, 1.5, -2.45, 2.45 ]

    # lidar_flag_ranges is a feature that requires a special build of the LuminLib library.
    # This setting for [MIN, MAX] range is to help eliminate unwanted points from the sample.
    # Points with range < MIN will have bit0=1 of its 'reflectance' value (in the LuminLib code).
    # Points with range > MAX will have bit1=1 of its 'reflectance' value.
    # [MIN, MAX] are in meters.
    # Set these values to:
    #  MIN=distance from this lidar to the farthest corner of your vehicle in the lidar FOV
    #   (this is a flag for the device driver to check the point against vehicle_polygon (above))
    #  MAX=distance of samples to be dropped because they're too far away.
    # Set to [0.0, 1000000.0] to disable
    lidar_flag_ranges: [3.7, 100.0]

    # if False, data are published with sensor data QoS. This is preferrable
    # for production but default QoS is needed for rosbag.
    # See: https://github.com/ros2/rosbag2/issues/125
    use_system_default_qos: False

    # Mask-like-string used to define the data processors that should be
    # activated upon startup of the driver. This will determine the topics
    # that are available for client applications to consume. The defacto
    # reference for these values are defined in:
    # `include/ros2_luminar/H3/processor_factories.hpp`
    #
    # The available data processors are:
    # PCL           - Provides a point cloud encoding of a LiDAR scan with x,y,z,intensity
    # PCL_EXTENDED  - Provides a point cloud encoding of a LiDAR scan with x,y,z,intensity,ring,time
    h3_proc_mask: PCL_EXTENDED

    # Lidar buffer size. Default to 12MB, since at a 1Hz update rate, the unit
    # can produce ~702K points, needing 11.2M bytes.
    buffer_size: 12582912
