nif_points_preprocessor_nodes:
  ros__parameters:
    # point concat filter
    input_topics : '[/luminar_front_points, /luminar_left_points, /luminar_right_points]',
    output_topic : '/merged/lidar',
    output_frame_id : 'center_of_gravity',                    

    # ego-shape filter
    left_lower_distance : 0.5,
    right_lower_distance : 0.5,
    rear_lower_distance : 2.2,
    front_lower_distance : 1.5,
    left_upper_distance : 30.0,
    right_upper_distance : 30.0,
    rear_upper_distance : 50.0,
    front_upper_distance : 50.0,
    height_lower_distance : -0.7,
    height_upper_distance : 0.5,
    resolution : 0.25,
    count_threshold : 3.,
    normal_angle_thres : 50.,
    ransac_pts_thresh : 200,
