//
// Created by usrg on 7/28/21.
//

#ifndef NIFSYSTEMSTATUSMANAGER_SYSTEM_STATUS_MANAGER_H
#define NIFSYSTEMSTATUSMANAGER_SYSTEM_STATUS_MANAGER_H

class SystemStatusManager
{

};

#endif // NIFSYSTEMSTATUSMANAGER_SYSTEM_STATUS_MANAGER_H
