session_name: nif_bag_play
windows: 
  - window_name: ROSBAG PLAY Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/media/LaCie/Dev12-bag/2022.01.03/VEH4_LVMS_RUN-01_2022-01-03
      - export ROS_DOMAIN_ID=33
      - export TRACK=LVMS
      - echo $TRACK
    panes:
    - shell_command:
        # - ros2 bag play autonomy_2021-09-29_14-57-31/ --topics /bvs_localization/ltp_odom /system/status /raptor_dbw_interface/wheel_speed_report /planning/graph/path_global /control_joint_lqr/lqr_error #LOR_0929_yaw_1

    - shell_command:
      # - ros2 bag play autonomy_2021-10-21_15-38-00/ --read-ahead-queue-size 10000 -r 1 -l # 2021.10.18
      - ros2 bag play autonomy_2022-01-03_11-47-13/ --read-ahead-queue-size 10000 -r1 --remap /ghost/odometry:=/remap1 /ghost/marker:=/remap2
    - shell_command:
      - ros2 run plotjuggler plotjuggler -l /home/usrg/nif/operations/config/plotjuggler_config_control_hk.xml

  - window_name: Algorithm Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/nif
      - export ROS_DOMAIN_ID=33
      - export TRACK=LVMS
      - echo $TRACK
    panes:
      - shell_command:
          # - ros2 launch nif_localization_nodes test.launch.py
      - shell_command:
          # - ros2 launch nif_points_preprocessor_nodes deploy.launch.py
      - shell_command:
          # - ros2 launch nif_multilayer_planning_nodes deploy.launch.py
      - shell_command:
          # - ros2 launch nif_aw_localization_nodes deploy.launch.py
      - shell_command:
          # - ros2 launch nif_costmap_generator deploy.launch.py
      - shell_command:
          # - ros2 bag record /aw_localization/ekf/odom /aw_localization/ekf/error /localization/ekf/odom /localization/ekf/odom_bestpos /bvs_localization/ltp_odom /novatel_bottom/insstdev /novatel_bottom/bestpos /novatel_bottom/inspva /novatel_bottom/bestvel /novatel_bottom/imu/data /out_localization_error
      - shell_command:
          # - ros2 topic echo /aw_localization/ekf/status

  - window_name: Monitoring Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/nif/src/perception/nif_localization_nodes/launch
      - export ROS_DOMAIN_ID=33
      - export TRACK=LVMS
      - echo $TRACK
    panes:
      - shell_command:
          - rviz2 -d /home/usrg/nif/src/perception/nif_localization_nodes/launch/navi.hk.rviz

  - window_name: Control Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/nif
      - export ROS_DOMAIN_ID=33
      - export TRACK=LVMS # for nif_launch base.launch.py
      - echo $TRACK
    panes:
      - shell_command:
          - ros2 launch nif_launch base.launch.py
      - shell_command:
          # - ros2 launch nif_dynamic_planning_nodes deploy.launch.py
      - shell_command:
          - ros2 launch nif_velocity_planning_node bag.launch.py
      - shell_command:
          - ros2 launch nif_control_joint_lqr_nodes bag.launch.py
      - shell_command:
          - ros2 launch nif_adaptive_cruise_control_node sim.launch.py
      - shell_command:
          - ros2 launch nif_accel_control_nodes bag.launch.py
          

  # - window_name: record Tab
  #   layout: tiled
  #   shell_command_before:
  #     - source /home/usrg/dev_ws/install/setup.bash && cd /home/usrg/dev_ws/src/bag
  #   panes:
  #     - shell_command:
  #         - ros2 bag record /luminar_front_points /luminar_left_points /novatel_bottom/bestpos /novatel_bottom/inspva
