session_name: nif_bag_play
windows: 
  - window_name: ROSBAG PLAY Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/Downloads/
      - export ROS_DOMAIN_ID=80
      - export TRACK=LVMS
    panes:
      - shell_command:
          - ros2 bag play 2021-12-01-VEH8-LVMS-RUN-2/sensors_2021-12-01_18-35-36

      - shell_command:
          # - ros2 launch nif_points_preprocessor_nodes deploy.launch.py
          # - ros2 launch nif_costmap_generator deploy.launch.py
          - ros2 launch nif_launch base.launch.py
          # - export ROS_DOMAIN_ID=80
          # - export TRACK=LVMS
          # - ros2 bag play sensors_2021-09-16_10-23-21 --topics /bvs_localization/ltp_odom /novatel_bottom/bestvel /novatel_bottom/bestvel /novatel_bottom/bestpos /novatel_bottom/inspva /novatel_top/bestpos /novatel_top/inspva /novatel_bottom/imu/data /novatel_top/imu/data /raptor_dbw_interface/wheel_speed_report

  - window_name: Algorithm Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/nif
      - export ROS_DOMAIN_ID=80
      - export TRACK=LVMS
    panes:
      - shell_command:
          # - ros2 launch nif_aw_localization_nodes default.launch.py
          - ros2 launch nif_aw_localization_bestgnss_nodes deploy.launch.py

      - shell_command:
          # - ros2 bag record /aw_localization/ekf/odom /localization/ekf/odom /localization/ekf/odom_bestpos /bvs_localization/ltp_odom /novatel_bottom/insstdev /novatel_bottom/bestpos /novatel_bottom/inspva /novatel_bottom/bestvel /novatel_bottom/imu/data /out_localization_error
          # - ros2 run rawimu2sensorimu subpub

  - window_name: Monitoring Tab
    layout: tiled
    shell_command_before:
      - source /home/usrg/nif/install/setup.bash && cd /home/usrg/nif/src/perception/nif_localization_nodes/launch
      - export ROS_DOMAIN_ID=80
      - export TRACK=LVMS
    panes:
      - shell_command:
          - rviz2