/**:
  ros__parameters:
    cycle_time_ms: 10
    # Only one of the three control command topics need be specified
    # "raw", "basic" or "high_level"
    control_command: "basic"
    ssc:
      front_axle_to_cog: 1.228
      rear_axle_to_cog: 1.5618
      max_yaw_rate: 1.5708
      steering_gear_ratio: 9.0 #DO12
      acc_pedal_min_limit: 0.0
      acc_pedal_max_limit: 100.0
      gear_min: 0
      gear_max: 6
      brake_pressure_min_limit: 0.0
      brake_pressure_max_limit: 5516.0
      steering_min_limit: -210.0
      steering_max_limit: 210.0
      joy_enabled: false

    state_machine:
      gear_shift_velocity_threshold_mps: 0.5
      acceleration_limits:
        min: -5.0
        max: 15.0
        threshold: 1.0
      front_steer_limits:
        min: -0.533
        max: 0.533
        threshold: 0.3
      time_step_ms: 100
      timeout_acceleration_mps2: 3.0
      state_transition_timeout_ms: 3000
      gear_shift_accel_deadzone_mps2: 0.5

